// <auto-generated />
using System;
using Clyvo.Insights.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Clyvo.Insights.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(InsightsDbContext))]
    [Migration("20260906214704_CriaSnapshotCoorte")]
    partial class CriaSnapshotCoorte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clyvo.Insights.Domain.Metas.MetaIndicador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_META_INDICADOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("DS_INDICADOR");

                    b.Property<decimal>("LimiarPercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("NR_LIMIAR_PERCENTUAL");

                    b.HasKey("Id");

                    b.HasIndex("IdClinica", "Indicador")
                        .IsUnique()
                        .HasDatabaseName("UK_INS_META_CLINICA_INDIC");

                    b.ToTable("INS_META_INDICADOR", (string)null);
                });

            modelBuilder.Entity("Clyvo.Insights.Domain.Projecoes.SnapshotCoorte", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SNAPSHOT_COORTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ConsultasAtribuiveis")
                        .HasPrecision(12, 2)
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("NR_CONSULTAS_ATRIBUIVEIS");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_REFERENCIA");

                    b.Property<decimal>("DeltaPontosPercentuais")
                        .HasPrecision(7, 2)
                        .HasColumnType("DECIMAL(7,2)")
                        .HasColumnName("NR_DELTA_PP");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<int>("ObrigacoesResolvidasControle")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_RESOLVIDAS_CONTROLE");

                    b.Property<int>("ObrigacoesResolvidasTratado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_RESOLVIDAS_TRATADO");

                    b.Property<decimal>("ReceitaRecuperada")
                        .HasPrecision(14, 2)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnName("VL_RECEITA_RECUPERADA");

                    b.Property<decimal?>("TicketMedio")
                        .HasPrecision(12, 2)
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("VL_TICKET_MEDIO");

                    b.HasKey("Id");

                    b.HasIndex("IdClinica", "DataReferencia")
                        .IsUnique()
                        .HasDatabaseName("UK_INS_SNAPSHOT_CLIN_DATA");

                    b.ToTable("INS_SNAPSHOT_COORTE", (string)null);
                });

            modelBuilder.Entity("Clyvo.Insights.Infrastructure.Persistencia.Leitura.PainelCoorteView", b =>
                {
                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_GRUPO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<int>("ObrigacoesCumpridas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_CUMPRIDAS");

                    b.Property<int>("ObrigacoesResolvidas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_OBRIGACOES");

                    b.Property<int>("PetsDistintos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_PETS");

                    b.Property<decimal?>("TicketMedio")
                        .HasPrecision(12, 2)
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("VL_TICKET_MEDIO");

                    b.ToTable((string)null);

                    b.ToView("VW_CLV_PAINEL_COORTE", (string)null);
                });

            modelBuilder.Entity("Clyvo.Insights.Infrastructure.Persistencia.Leitura.PainelReceitaView", b =>
                {
                    b.Property<int>("AlcancaramAgendada")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_AGENDADAS");

                    b.Property<int>("AlcancaramNotificada")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_NOTIFICADAS");

                    b.Property<int>("AlcancaramRespondida")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_RESPONDIDAS");

                    b.Property<int>("Cumpridas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_CUMPRIDAS");

                    b.Property<string>("GrupoControle")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FL_GRUPO_CONTROLE");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("MES_REFERENCIA");

                    b.Property<int>("Perdidas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_PERDIDAS");

                    b.Property<int>("Total")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_OBRIGACOES");

                    b.Property<decimal>("ValorPerdido")
                        .HasPrecision(14, 2)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnName("VL_PERDIDO");

                    b.Property<decimal>("ValorRecuperado")
                        .HasPrecision(14, 2)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnName("VL_RECUPERADO");

                    b.ToTable((string)null);

                    b.ToView("VW_CLV_PAINEL_RECEITA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
