// <auto-generated />
using System;
using Clyvo.Insights.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Clyvo.Insights.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(InsightsDbContext))]
    partial class InsightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clyvo.Insights.Domain.Metas.MetaIndicador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_META_INDICADOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("DS_INDICADOR");

                    b.Property<decimal>("LimiarPercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("NR_LIMIAR_PERCENTUAL");

                    b.HasKey("Id");

                    b.HasIndex("IdClinica", "Indicador")
                        .IsUnique()
                        .HasDatabaseName("UK_INS_META_CLINICA_INDIC");

                    b.ToTable("INS_META_INDICADOR", (string)null);
                });

            modelBuilder.Entity("Clyvo.Insights.Infrastructure.Persistencia.Leitura.PainelCoorteView", b =>
                {
                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_GRUPO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<int>("ObrigacoesCumpridas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_CUMPRIDAS");

                    b.Property<int>("ObrigacoesResolvidas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_OBRIGACOES");

                    b.Property<int>("PetsDistintos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QT_PETS");

                    b.Property<decimal?>("TicketMedio")
                        .HasPrecision(12, 2)
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("VL_TICKET_MEDIO");

                    b.ToTable((string)null);

                    b.ToView("VW_CLV_PAINEL_COORTE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
